In [1]:
import numpy as np
import pandas as pd

In [101]:
data=pd.read_csv("Sample_sheet.csv",encoding="utf-8")

In [102]:
data

Sr. no     Name  Year of Exp     Domain  Relevent Exp  Income(USD)  \
0       1   Pravin           10  Marketing           8.0       4000.0   
1       2    Sonal           11         IT           6.0       2500.0   
2       3   Vedika            1         IT           1.0       2000.0   
3       4   Sachin           15         HR          11.0       6000.0   
4       5  Sakshat            4  Marketing           3.0       3500.0   
5       6    Anita            6  Operation           5.0       3400.0   
6       7   Ankita           19        NaN           NaN          NaN   
7       8   Pratik            9      Sales           9.0       5800.0   
8       9     Maya            5       NICU           4.0       6300.0   
9      10    Virat            6         HR           5.0       4500.0   

  Marital Status  Number of Siblings  Expenditure  
0        Married                   2         4500  
1        Married                   1          200  
2      Unmarried                   2          300  
3        Married                   4         5000  
4      Unmarried                   5         6000  
5        Married                   2         4000  
6            NaN                   3         1500  
7      Unmarried                   4         1600  
8        Married                   1         1800  
9      Unmarried                   2         1700

In [28]:
data["dummy"]=np.zeros((10))

In [29]:
data.shape

(10, 10)

In [30]:
data.size

100

In [31]:
data.dtypes

Sr. no                  int64
Name                   object
Year of Exp             int64
Domain                 object
Relevent Exp          float64
Income                float64
Marital Status         object
Number of Siblings      int64
Expenditure             int64
dummy                 float64
dtype: object

In [103]:
data.describe()

Sr. no  Year of Exp  Relevent Exp  Income(USD)  Number of Siblings  \
count  10.00000    10.000000      9.000000     9.000000           10.000000   
mean    5.50000     8.600000      5.777778  4222.222222            2.600000   
std     3.02765     5.399588      3.113590  1549.014023            1.349897   
min     1.00000     1.000000      1.000000  2000.000000            1.000000   
25%     3.25000     5.250000      4.000000  3400.000000            2.000000   
50%     5.50000     7.500000      5.000000  4000.000000            2.000000   
75%     7.75000    10.750000      8.000000  5800.000000            3.750000   
max    10.00000    19.000000     11.000000  6300.000000            5.000000   

       Expenditure  
count    10.000000  
mean   2660.000000  
std    2042.982569  
min     200.000000  
25%    1525.000000  
50%    1750.000000  
75%    4375.000000  
max    6000.000000

In [104]:
data.isna().any()

Sr. no                False
Name                  False
Year of Exp           False
Domain                 True
Relevent Exp           True
Income(USD)            True
Marital Status         True
Number of Siblings    False
Expenditure           False
dtype: bool

In [88]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Name            10 non-null     object 
 1   Year of Exp     10 non-null     int64  
 2   Domain          9 non-null      object 
 3   Relevent Exp    9 non-null      float64
 4   Income          9 non-null      float64
 5   Marital Status  9 non-null      object 
 6   Expenditure     10 non-null     int64  
 7   dummy           10 non-null     float64
dtypes: float64(3), int64(2), object(3)
memory usage: 768.0+ bytes


In [36]:
data.drop("Number of Siblings",axis=1)

Sr. no     Name  Year of Exp     Domain  Relevent Exp  Income   \
0       1   Pravin           10  Marketing           8.0   4000.0   
1       2    Sonal           11         IT           6.0   2500.0   
2       3   Vedika            1         IT           1.0   2000.0   
3       4   Sachin           15         HR          11.0   6000.0   
4       5  Sakshat            4  Marketing           3.0   3500.0   
5       6    Anita            6  Operation           5.0   3400.0   
6       7   Ankita           19        NaN           NaN      NaN   
7       8   Pratik            9      Sales           9.0   5800.0   
8       9     Maya            5       NICU           4.0   6300.0   
9      10    Virat            6         HR           5.0   4500.0   

  Marital Status  Expenditure  dummy  
0        Married         4500    0.0  
1        Married          200    0.0  
2      Unmarried          300    0.0  
3        Married         5000    0.0  
4      Unmarried         6000    0.0  
5        Married         4000    0.0  
6            NaN         1500    0.0  
7      Unmarried         1600    0.0  
8        Married         1800    0.0  
9      Unmarried         1700    0.0

In [37]:
#Before using inplace=True
data


Sr. no     Name  Year of Exp     Domain  Relevent Exp  Income   \
0       1   Pravin           10  Marketing           8.0   4000.0   
1       2    Sonal           11         IT           6.0   2500.0   
2       3   Vedika            1         IT           1.0   2000.0   
3       4   Sachin           15         HR          11.0   6000.0   
4       5  Sakshat            4  Marketing           3.0   3500.0   
5       6    Anita            6  Operation           5.0   3400.0   
6       7   Ankita           19        NaN           NaN      NaN   
7       8   Pratik            9      Sales           9.0   5800.0   
8       9     Maya            5       NICU           4.0   6300.0   
9      10    Virat            6         HR           5.0   4500.0   

  Marital Status  Number of Siblings  Expenditure  dummy  
0        Married                   2         4500    0.0  
1        Married                   1          200    0.0  
2      Unmarried                   2          300    0.0  
3        Married                   4         5000    0.0  
4      Unmarried                   5         6000    0.0  
5        Married                   2         4000    0.0  
6            NaN                   3         1500    0.0  
7      Unmarried                   4         1600    0.0  
8        Married                   1         1800    0.0  
9      Unmarried                   2         1700    0.0

In [38]:
data.drop("Number of Siblings",axis=1,inplace=True)

In [39]:
#After using inplace=True
data


Sr. no     Name  Year of Exp     Domain  Relevent Exp  Income   \
0       1   Pravin           10  Marketing           8.0   4000.0   
1       2    Sonal           11         IT           6.0   2500.0   
2       3   Vedika            1         IT           1.0   2000.0   
3       4   Sachin           15         HR          11.0   6000.0   
4       5  Sakshat            4  Marketing           3.0   3500.0   
5       6    Anita            6  Operation           5.0   3400.0   
6       7   Ankita           19        NaN           NaN      NaN   
7       8   Pratik            9      Sales           9.0   5800.0   
8       9     Maya            5       NICU           4.0   6300.0   
9      10    Virat            6         HR           5.0   4500.0   

  Marital Status  Expenditure  dummy  
0        Married         4500    0.0  
1        Married          200    0.0  
2      Unmarried          300    0.0  
3        Married         5000    0.0  
4      Unmarried         6000    0.0  
5        Married         4000    0.0  
6            NaN         1500    0.0  
7      Unmarried         1600    0.0  
8        Married         1800    0.0  
9      Unmarried         1700    0.0

In [44]:
print("Printing Values : ",data["Domain"].values)
print("Printing unique values : ",data["Domain"].unique())

Printing Values :  ['Marketing' 'IT' 'IT' 'HR' 'Marketing' 'Operation' nan 'Sales' 'NICU'
 'HR']
Printing unique values :  ['Marketing' 'IT' 'HR' 'Operation' nan 'Sales' 'NICU']


In [54]:
data.drop("Sr. no",axis=1,inplace=True)

In [89]:
data.corr()

Year of Exp  Relevent Exp   Income   Expenditure  dummy
Year of Exp      1.000000      0.932059  0.415526     0.038678    NaN
Relevent Exp     0.932059      1.000000  0.592071     0.294532    NaN
Income           0.415526      0.592071  1.000000     0.227730    NaN
Expenditure      0.038678      0.294532  0.227730     1.000000    NaN
dummy                 NaN           NaN       NaN          NaN    NaN

In [59]:
corr_data=data.drop("dummy",axis=1).corr()

In [60]:
corr_data

Year of Exp  Relevent Exp   Income   Expenditure
Year of Exp      1.000000      0.932059  0.415526     0.038678
Relevent Exp     0.932059      1.000000  0.592071     0.294532
Income           0.415526      0.592071  1.000000     0.227730
Expenditure      0.038678      0.294532  0.227730     1.000000

In [90]:
data.isna().any()


Name              False
Year of Exp       False
Domain             True
Relevent Exp       True
Income             True
Marital Status     True
Expenditure       False
dummy             False
dtype: bool

In [64]:
data_=data.isna().sum()

In [65]:
data_

Name              0
Year of Exp       0
Domain            1
Relevent Exp      1
Income            1
Marital Status    1
Expenditure       0
dummy             0
dtype: int64

In [112]:
from sklearn.impute import SimpleImputer
imp_constant=SimpleImputer(strategy="constant",fill_value=1111)
imp_mean=SimpleImputer(strategy="mean")
imp_median=SimpleImputer(strategy="median")
imp_mode=SimpleImputer(strategy="most_frequent")
print("Now we are using Simple imputer to fill missing valudes")

Now we are using Simple imputer to fill missing valudes


In [106]:
data[["Income(USD)"]]

Income(USD)
0       4000.0
1       2500.0
2       2000.0
3       6000.0
4       3500.0
5       3400.0
6          NaN
7       5800.0
8       6300.0
9       4500.0

In [108]:
imp_constant.fit_transform(data[["Income(USD)"]])

array([[4000.],
       [2500.],
       [2000.],
       [6000.],
       [3500.],
       [3400.],
       [1111.],
       [5800.],
       [6300.],
       [4500.]])

In [109]:
imp_mean.fit_transform(data[["Income(USD)"]])

array([[4000.        ],
       [2500.        ],
       [2000.        ],
       [6000.        ],
       [3500.        ],
       [3400.        ],
       [4222.22222222],
       [5800.        ],
       [6300.        ],
       [4500.        ]])

In [110]:
imp_median.fit_transform(data[["Income(USD)"]])

array([[4000.],
       [2500.],
       [2000.],
       [6000.],
       [3500.],
       [3400.],
       [4000.],
       [5800.],
       [6300.],
       [4500.]])

In [113]:
imp_mode.fit_transform(data[["Income(USD)"]])

array([[4000.],
       [2500.],
       [2000.],
       [6000.],
       [3500.],
       [3400.],
       [2000.],
       [5800.],
       [6300.],
       [4500.]])