In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer

In [2]:
cancer_data = load_breast_cancer()

In [3]:
print(cancer_data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [4]:
features = pd.DataFrame(cancer_data.data, columns=cancer_data.feature_names)
target = pd.DataFrame(cancer_data.target, columns=['Target'])

In [5]:
features.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [18]:
target.head(100)

Target
0        0
1        0
2        0
3        0
4        0
..     ...
95       0
96       1
97       1
98       1
99       0

[100 rows x 1 columns]

In [7]:
target.Target.value_counts()

1    357
0    212
Name: Target, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, classification_report

In [9]:
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=10)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(426, 30)
(143, 30)
(426, 1)
(143, 1)


In [10]:
my_logreg_model = LogisticRegression().fit(X_train, y_train)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
my_logreg_preds_train = my_logreg_model.predict(X_train)

my_logreg_preds_test = my_logreg_model.predict(X_test)

print('Accuracy on Train set : ',accuracy_score(y_train, my_logreg_preds_train))
print('Accuracy on Test set` : ',accuracy_score(y_test, my_logreg_preds_test))
      

Accuracy on Train set :  0.9436619718309859
Accuracy on Test set` :  0.9300699300699301


In [12]:
# Prediction Probabilities
list(zip(my_logreg_model.predict_proba(X_train), my_logreg_model.predict(X_train)))

[(array([3.12720673e-04, 9.99687279e-01]), 1),
 (array([1.69065679e-04, 9.99830934e-01]), 1),
 (array([1.00000000e+00, 7.06703461e-13]), 0),
 (array([3.26890386e-05, 9.99967311e-01]), 1),
 (array([0.00364724, 0.99635276]), 1),
 (array([0.03978986, 0.96021014]), 1),
 (array([1.58236997e-05, 9.99984176e-01]), 1),
 (array([9.99966281e-01, 3.37191985e-05]), 0),
 (array([5.55281078e-05, 9.99944472e-01]), 1),
 (array([1.00000000e+00, 9.35212861e-12]), 0),
 (array([0.10766686, 0.89233314]), 1),
 (array([6.59033325e-05, 9.99934097e-01]), 1),
 (array([0.00868763, 0.99131237]), 1),
 (array([9.99999986e-01, 1.41863474e-08]), 0),
 (array([9.18796215e-04, 9.99081204e-01]), 1),
 (array([0.0012025, 0.9987975]), 1),
 (array([9.99973623e-01, 2.63769618e-05]), 0),
 (array([6.07247975e-04, 9.99392752e-01]), 1),
 (array([1.77550619e-05, 9.99982245e-01]), 1),
 (array([5.24500428e-04, 9.99475500e-01]), 1),
 (array([0.00113526, 0.99886474]), 1),
 (array([0.00279077, 0.99720923]), 1),
 (array([9.99971945e-01,

In [13]:
print('Confusion Matrix on Train set :\n', confusion_matrix(y_train, my_logreg_preds_train))

Confusion Matrix on Train set :
 [[146  14]
 [ 10 256]]


In [14]:
print('Confusion Matrix on Test set :\n', confusion_matrix(y_test, my_logreg_preds_test))

Confusion Matrix on Test set :
 [[48  4]
 [ 6 85]]


In [15]:
print('Precision on Train set : ',precision_score(y_train, my_logreg_preds_train))
print('Precision on Test set : ',precision_score(y_test, my_logreg_preds_test))

print('\n')

print('Recall on Train set : ',recall_score(y_train, my_logreg_preds_train))
print('Recall on Test set : ',recall_score(y_test, my_logreg_preds_test))

print('\n')

print('F1-Score on Train set : ',f1_score(y_train, my_logreg_preds_train))
print('F1-Score on Test set : ',f1_score(y_test, my_logreg_preds_test))

Precision on Train set :  0.9481481481481482
Precision on Test set :  0.9550561797752809


Recall on Train set :  0.9624060150375939
Recall on Test set :  0.9340659340659341


F1-Score on Train set :  0.955223880597015
F1-Score on Test set :  0.9444444444444444


In [16]:
print('Classification Report on Train set : ')
print(classification_report(y_train, my_logreg_preds_train))

Classification Report on Train set : 
              precision    recall  f1-score   support

           0       0.94      0.91      0.92       160
           1       0.95      0.96      0.96       266

    accuracy                           0.94       426
   macro avg       0.94      0.94      0.94       426
weighted avg       0.94      0.94      0.94       426



In [17]:
print('Classification Report on Test set : ')
print(classification_report(y_test, my_logreg_preds_test))

Classification Report on Test set : 
              precision    recall  f1-score   support

           0       0.89      0.92      0.91        52
           1       0.96      0.93      0.94        91

    accuracy                           0.93       143
   macro avg       0.92      0.93      0.93       143
weighted avg       0.93      0.93      0.93       143

